export const ICMPV6_TYPES = {
    DESTINATION_UNREACHABLE: 1,
    PACKET_TOO_BIG: 2,
    TIME_EXCEEDED: 3,
    PARAMETER_PROBLEM: 4,


    ECHO_REQUEST: 128,
    ECHO_REPLY: 129,

    NEIGHBOR_SOLICITATION: 135,
    NEIGHBOR_ADVERTISMENT: 136,
} as const;

export type ICMPV6_Type = typeof ICMPV6_TYPES[keyof typeof ICMPV6_TYPES];

export const ICMPV6_CODES = {
    [ICMPV6_TYPES.DESTINATION_UNREACHABLE]: {},
    [ICMPV6_TYPES.PACKET_TOO_BIG]: {},
    [ICMPV6_TYPES.TIME_EXCEEDED]: {},
    [ICMPV6_TYPES.PARAMETER_PROBLEM]: {},

    [ICMPV6_TYPES.ECHO_REQUEST]: 0,
    [ICMPV6_TYPES.ECHO_REPLY]: 0,
    [ICMPV6_TYPES.NEIGHBOR_SOLICITATION]: 0,
    [ICMPV6_TYPES.NEIGHBOR_ADVERTISMENT]: 0,

} as const;
